START TRANSACTION;

CREATE TABLE VEGETABLE
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
vegetable_name VARCHAR(255) NOT NULL,
unit VARCHAR(255) NOT NULL
);

CREATE TABLE PERSON
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
phonenumber VARCHAR(10) NOT NULL,
alias VARCHAR(255),
email VARCHAR(255),
location_id VARCHAR(255) NOT NULL,
address_id VARCHAR(255) NOT NULL,
user_type VARCHAR(255) NOT NULL 
);

CREATE TABLE ADDRESS
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
address1 VARCHAR(255) NOT NULL,
address2 VARCHAR(255),
city VARCHAR(255) NOT NULL,
state VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,
zipcode INT(6) NOT NULL
);

CREATE TABLE TRANSPORTATION
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
location VARCHAR(255) NOT NULL,
price DECIMAL(10,2) NOT NULL
);

CREATE TABLE TRANSACTIONS (
  id INT NOT NULL,
  person_id INT(10) NOT NULL,
  vegetable_id INT(10) NOT NULL,
  vegetable_quantity DECIMAL(19, 2) NOT NULL,
  unit_price INT NOT NULL,
  total_amount INT NOT NULL,
  bag_quantity INT NOT NULL,
  transaction_date DATETIME NOT NULL,
  UNIQUE INDEX transaction_id_unique (id ASC)
);

CREATE TABLE PAYMENT_TRANSACTIONS
(
 id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
 person_id INT(10) NOT NULL,
 payment_amount DECIMAL(19, 2) NOT NULL,
 remaining_balance DECIMAL(19, 2) NOT NULL,
 transaction_date DATETIME NOT NULL
);

CREATE TABLE ACCOUNT_BALANCES
(
 id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
 person_id INT(10) NOT NULL,
 balance DECIMAL(19, 2) NOT NULL
);

COMMIT;
