START TRANSACTION;

CREATE TABLE VEGITABLE
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
vegitable_name VARCHAR(255) NOT NULL,
units VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX vegitable_id_unique ON VEGITABLE (id);

CREATE TABLE PERSON
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
phonenumber INT(10) NOT NULL,
alias VARCHAR(255),
email VARCHAR(255),
location_id VARCHAR(255) NOT NULL,
address_id VARCHAR(255),
user_type VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX person_id_unique ON PERSON (id);

CREATE TABLE ADDRESS
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
address1 VARCHAR(255),
address2 VARCHAR(255),
city VARCHAR(255),
state VARCHAR(255),
country VARCHAR(255),
zipcode INT(6)
);
CREATE UNIQUE INDEX address_id_unique ON ADDRESS (id);

CREATE TABLE TRANSPORTATION
(
id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
location VARCHAR(255) NOT NULL,
price DECIMAL(10,2) NOT NULL
);
CREATE UNIQUE INDEX transportation_id_unique ON TRANSPORTATION (id);

CREATE TABLE TRANSACTIONS (
  id INT NOT NULL,
  vendor_id VARCHAR(255) NOT NULL,
  vegitable_id VARCHAR(255) NOT NULL,
  vegitable_quantity INT NOT NULL,
  unit_price INT NOT NULL,
  total_amount INT NOT NULL,
  quanty INT NOT NULL,
  bag_quantity INT NOT NULL,
  transaction_date DATETIME NOT NULL,
  UNIQUE INDEX transaction_id_unique (id ASC)
);

CREATE TABLE PAYMENT_TRANSACTIONS
(
 id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
 person_id INT(10) NOT NULL,
 payment_amount DECIMAL(19, 0) NOT NULL,
 remaining_balance DECIMAL(19, 0) NOT NULL,
 transaction_date DATETIME NOT NULL
);
CREATE UNIQUE INDEX payment_id_unique ON PAYMENT_TRANSACTIONS (id);

CREATE TABLE ACCOUNT_BALANCES
(
 id INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
 person_id INT(10) NOT NULL,
 balance DECIMAL(19, 0) NOT NULL
);
CREATE UNIQUE INDEX account_balances_id_unique ON ACCOUNT_BALANCES (id);

COMMIT;